config/routes.rb
DegreeCouncil::Application.routes.draw do

 
  
  resources :form_datas
  resources :questions
  resources :question_steps
  resources :forms
  
  get '/articles' => 'home#articles', as: :articles
  get '/home' => 'home#home', as: :home
  root 'home#index'

  post '/lead/store_lead' => 'application#store_lead'
  namespace :api do
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :answer, :presence => true, :on => :update
  

end

app/models/form.rb
class Form < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions , :allow_destroy => true

end

app/models/form_data.rb
class FormData < ActiveRecord::Base
  belongs_to :question
  belongs_to :visit
end

app/models/lead.rb
class Lead < ActiveRecord::Base

  ## Relationships
  has_many :visits
  belongs_to :provider

  attr_accessor :ipaddress

  accepts_nested_attributes_for :visits , :allow_destroy => true

  ## Validations

  ## Class Methods

  ## Instance Methods


end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :leads
end

app/models/question.rb
class Question < ActiveRecord::Base

  attr_accessor :ans_opt1, :ans_custom_1, :ans_custom_2

  belongs_to :form
  has_many :form_datas
  has_many :answers
  belongs_to :question_type
  accepts_nested_attributes_for :answers , :allow_destroy => true

  # Validations
  validates :question_name, :presence => true, :on => :update
  validates :answer_options, :presence => true, :on => :update
end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
  has_many :questions

  scope :option2, where("name = ? or name = ?", "radio", "checkbox")
  scope :option2plus, where("name = ? or name = ?", "dropdown", "radio")

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  ## Relationships
  belongs_to :lead
  has_many :form_datas
  ## Validations

  ## Class Methods

  ## Instance Methods

end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record
  protected

  def render_json(json)
    callback = params[:callback]
    response = begin
      if callback
        "#{callback}(#{json});"
      else
        json
      end
    end
    render({:content_type => :js, :text => response})
  end

  def bad_record
    render_json({:errors => "No Record Found!", :status => 404}.to_json)
  end

  def parameter_errors
    render_json({:errors => "You have supplied invalid parameter list.", :status => 404}.to_json)
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end
  
end

app/controllers/api/leads_controller.rb
class Api::LeadsController < Api::BaseController
   
  ## Store Information from other website
  def store_lead
    if params[:secret_key].present?
      provider = Provider.find_by_secret_key(params[:secret_key])
      if provider.present?
        lead = Lead.find_by_source_url_and_email(params[:lead][:source_url], params[:lead][:email])
        @lead = lead.present? ? lead : provider.leads.create(lead_params)
        visit = @lead.visits.build
        visit.ipaddress = params[:lead][:ipaddress]
        visit.visit_date = Time.now    
        visit.save
        render_json({:messages => "Ok", :status => 200}.to_json)
      else
        render_json({:errors => "Invalid Secret Key", :status => 404}.to_json)
      end
    else
      render_json({:errors => "Bad Request", :status => 400}.to_json)
    end
  end

  private

  def lead_params
    params.require(:lead).permit(:provider_id, :username, :firstname, :lastname, :email, :source_url, :latitude, :longitude, :city, :state, :country, :zipcode, :ipaddress)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  rescue_from ActiveRecord::RecordNotFound, :with => :bad_record


  protect_from_forgery with: :exception
 

  def store_lead
    if params[:secret_key].present?
      provider = Provider.find_by_secret_key(params[:secret_key])
      if provider.present?
        lead = Lead.find_by_source_url_and_email(params[:lead][:source_url], params[:lead][:email])
        @lead = lead.present? ? lead : provider.leads.create(lead_params)
        visit = @lead.visits.build
        visit.ipaddress = params[:lead][:ipaddress]
        visit.visit_date = Time.now    
        visit.save
        session[:visit_id] = visit.id
        #render_json({:messages => "Ok", :status => 200}.to_json)
        redirect_to home_path
      else
        render_json({:errors => "Invalid Secret Key", :status => 404}.to_json)
      end
    else
      render_json({:errors => "Bad Request", :status => 400}.to_json)
    end
  end

  private

  def lead_params
    params.require(:lead).permit(:provider_id, :username, :firstname, :lastname, :email, :source_url, :latitude, :longitude, :city, :state, :country, :zipcode, :ipaddress)
  end

  protected

  def render_json(json)
    callback = params[:callback]
    response = begin
      if callback
        "#{callback}(#{json});"
      else
        json
      end
    end
    render({:content_type => :js, :text => response})
  end

  def bad_record
    render_json({:errors => "No Record Found!", :status => 404}.to_json)
  end

  def parameter_errors
    render_json({:errors => "You have supplied invalid parameter list.", :status => 404}.to_json)
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

end

app/controllers/form_datas_controller.rb
class FormDatasController < ApplicationController

  def index

  end

  def create
    @visitor = Visit.find(session[:visit_id])
    ans = params[:question][:form_datas][:answer]
    if ans.present?
      ans.each do |a|
        FormData.create(:question_id => a.first.to_i, :answer => a.last, :visit_id => @visitor.id )
      end
    end
    session[:visit_id] = nil
    redirect_to form_data_path(@visitor.id)
  end

  def show
    @visitor = Visit.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :current_visitor, :only => [:home]
  
  def current_visitor
    if session[:visit_id].present? 
      @visitor = Visit.find(session[:visit_id])
    else
      @visitor = Visit.create(:ipaddress => request.remote_ip)
      session[:visit_id] = @visitor.id 
    end
  end

  def index
  end

  def articles
  end

  def home
    @providers = Provider.all
    @form_data = Question.new()
  end
end

app/controllers/question_steps_controller.rb
class QuestionStepsController < ApplicationController
  include Wicked::Wizard
  steps :question, :answer, :selecttype

  def show
    if session[:question_id].present?
      @question = Question.find(session[:question_id])
    else
      @question = Question.create
      session[:question_id] = @question.id
    end
    @answer = @question.answers.build unless @question.answers.present? 
    render_wizard
  end

  def update
    @question = Question.find(session[:question_id])
    @answer = @question.answers.build unless @question.answers.present? 
    if params[:question].present? && params[:question][:ansopt2].present?
      ansopt2 = params[:question][:ansopt2]
      if ansopt2.to_s == "yes-no"
        @question.answers.destroy_all
        @question.answers.create(:answer => "Yes")
        @question.answers.create(:answer => "No")
      elsif ansopt2.to_s == "true-false"
        @question.answers.destroy_all
        @question.answers.create(:answer => "True")
        @question.answers.create(:answer => "False")
      else
        @question.answers.destroy_all
        @question.answers.create(:answer => params[:question][:ans_custom_1])
        @question.answers.create(:answer => params[:question][:ans_custom_2])
      end
    end
    @question.update_attributes(question_params)
    render_wizard @question
  end


  private

  def finish_wizard_path
    session[:question_id] = nil
    root_url
  end

  def question_params
    params.require(:question).permit(:ansopt2, :question_type_id, :answer_options, :question_name, :form_id, :answers_attributes => [:id, :answer, :question_id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_data_helper.rb
module FormDataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/question_steps_helper.rb
module QuestionStepsHelper
end

app/views/form_datas/show.html.erb
<h1> Information </h1>
<table>
  <% @visitor.form_datas.each do |data| %>
  <tr>
    <td><%= data.question.question_name %> : </td> 
    <td>
      <% if data.answer.to_s == "true" %>
        Yes
      <% elsif data.answer.to_s == "false" %>
        No
      <% else %>
        <%= data.answer %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/home/_leads.html.erb
<% if @providers.present? %>
  <h3>Leads</h3>
  <% @providers.each do |provider| %>
    <% if provider.leads.present? %>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Provider</th>
              <th>Username</th>
              <th>Firstname</th>
              <th>Email</th>
              <th>Source URL</th>
              <th>City</th>
              <th>State</th>
              <th>Country</th>
              <th>Visit Count</th>
              <th>Lead Created Date</th>
            </tr>
          </thead>
          <tbody>
            <% provider.leads.each do |lead| %>
              <tr>
                <td><%= lead.provider.name %></td>
                <td><%= lead.username if lead.username.present? %></td>
                <td><%= lead.firstname if lead.firstname.present? %></td>
                <td><%= lead.email if lead.email.present? %></td>
                <td><%= lead.source_url if lead.source_url.present? %></td>
                <td><%= lead.city if lead.city.present? %></td>
                <td><%= lead.state if lead.state.present? %></td>
                <td><%= lead.country if lead.country.present? %></td>
                <td><%= lead.visits.count %></td>
                <td><%= lead.created_at.strftime("%b %m, %Y %h:%m")%></td>
              </tr>
            <% end %>    
          </tbody>
        </table>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/home/_old3.html.erb
<%= simple_form_for @student, :validate => true do |f| %>
            <fieldset>  
            
              <% unless flash[:notice].nil? %>
                <div id ="notice" class="text-info"><%= flash[:notice] %></div>
              <% end %>
              <% unless flash[:warning].nil? %>
                <div id ="alert" class="text-info"><%= flash[:warning] %></div>
              <% end %>
              <% unless flash[:alert].nil? %>
                <div id ="alert" class="text-info"><%= flash[:alert] %></div>
              <% end %>
            
            <div class="yellow">
            
            
            
            <%= f.input :highest_level_of_education, 
                # :label => "What is your highest level of</br>education so far?",
                :label => false,
                :collection => 
                  [
                    ["Still in High School", 0 ], 
                    ["GED", 1 ],        
                    ["High School Diploma", 2 ],  
                    ["Some College (less than two years)", 3 ], 
                    ["Some College (more than two years)", 4 ],
                    ["Associate's Degree", 5 ],   
                    ["Bachelor's Degree", 6 ],  
                    # ["Post-Graduate Study", 7 ],   
                    ["Master's Degree", 8 ],    
                    ["Doctoral Degree", 9 ],    
                    # ["Nursing Diploma", 10 ]  # or between 5,6? 
                  
                  ],
                :prompt => "Highest level of
                  education so far",
                :wrapper_html => { :id => 'edu_level'},
                :required => true
               %></div>
          
              <!-- prepop this with a choice consistent with the user's selected hloe; show alert if he changes it to something that won't work? -->
              <div class="yellow"><%= f.input :degree_sought,
               :label => false,
                :wrapper_html => { :id => 'degree_level'},
                :collection =>
                  [ 
                    ["Associate's","1"],
                    ["Bachelor's","2"],
                    ["Master's","3"],
                    ["Doctoral","4"]
                    #["Professional Certificate","5"]
                  ],  
                :prompt => 'What degree is next for you?',
                :input_html => { :id => 'degrees_select'},
                :required => true 
              %></div>

              <!--- Area of Study ( Discipline ) —————————— -->
              <div class="yellow"><%= f.input :area_of_study, 
                # :label => "Area of Study",
                :wrapper_html => { :id => 'area_of_study'},
                :label => false,
                :collection =>
                  [
                    ["Business",1], 
                    ["Criminal Justice",2], 
                    ["Education",3],    
                    ["Engineering & Science", 4], 
                    ["Fire & Emergency Mgmt", 5],
                    # ["Environment",6],        
                    ["Healthcare",7], 
                    ["Information Technology",8], # or CS/IT  
                    ["Legal/Paralegal Studies",9],  
                    ["Liberal Arts",10],  
                    ["Nursing",11],
                    ["Psychology & Counseling", 12],   
                    ["Social Services",13],
                    ["Web/Graphic Design",14],
                    ["Theology",15]
                    
                  ],
                :prompt => "Area of Study",
                :input_html => { :id => 'disciplines_select' },
                :required => true           
              %></div>
          
            <%= f.submit "         Start Search         ", :class => 'btn btn-warning btn-mine green-button' %>
            <!-- this will go to Student#create -->
            </fieldset>
          <% end %> <!-- end simple_form do block -->

app/views/home/articles.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p></p> 
  <% lead = {'lead[username]'=>'username', 'lead[firstname]'=>'firstname', 'lead[lastname]' => 'lastname', 'lead[email]' => 'emel@yopmail.com', 'lead[source_url]' => request.original_url, 'lead[latitude]' => 75.10, 'lead[longitude]' => 23.80, 'lead[ipaddress]' => '127.0.0.1', 'lead[city]' => 'city', 'lead[state]' => 'state', 'lead[country]' => 'India', 'lead[zipcode]' => '123456', 'secret_key' => 'f4cc650a735ca9b699f0ac1bc7d70a4c' } %>


  <p>
    <%= link_to "Lead Post", lead_store_lead_url(lead), :method => 'POST', :title => "", :class => "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p></p>
  <p>
    <%= link_to "Login", articles_path, :class => "btn btn-primary btn-lg", :role => "button" %>
    <%= link_to "W/o Login", articles_path, :class => "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/_old.html.erb
_

<!DOCTYPE html>
<html>
<head>
  <title>DegreeCouncil</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">DegreeCouncil</a>
        </div>
        <div class="navbar-collapse collapse">
          <!--
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul> -->
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container theme-showcase" role="main">
<%= yield %>
</div>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

</body>
</html>

app/views/layouts/_old2.html.erb
<form accept-charset="UTF-8" action="/students" class="simple_form new_student" id="new_student" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="csP+D6UGCuic1HGrCbz8e9ftjTYzgg5NwnG5lRVA56Q="></div>
            <fieldset>  
            
            
            <div class="yellow">
            
            
            
            <div class="control-group select required student_highest_level_of_education" id="edu_level"><div class="controls"><select class="select required" id="student_highest_level_of_education" name="student[highest_level_of_education]"><option value="">Highest level of
                  education so far</option>
<option value="0">Still in High School</option>
<option value="1">GED</option>
<option value="2">High School Diploma</option>
<option value="3">Some College (less than two years)</option>
<option value="4">Some College (more than two years)</option>
<option value="5">Associate's Degree</option>
<option value="6">Bachelor's Degree</option>
<option value="8">Master's Degree</option>
<option value="9">Doctoral Degree</option></select></div></div></div>
          
              <!-- prepop this with a choice consistent with the user's selected hloe; show alert if he changes it to something that won't work? -->
              <div class="yellow inactive"><div class="control-group select required student_degree_sought" id="degree_level"><div class="controls"><select class="select required" id="degrees_select" name="student[degree_sought]" disabled="disabled"><option value="">What degree is next for you?</option>
<option value="1">Associate's</option>
<option value="2">Bachelor's</option>
<option value="3">Master's</option>
<option value="4">Doctoral</option></select></div></div></div>

              <!--- Area of Study ( Discipline ) —————————— -->
              <div class="yellow inactive"><div class="control-group select required student_area_of_study" id="area_of_study"><div class="controls"><select class="select required" id="disciplines_select" name="student[area_of_study]" disabled="disabled"><option value="">Area of Study</option>
<option value="1">Business</option>
<option value="2">Criminal Justice</option>
<option value="3">Education</option>
<option value="4">Engineering &amp; Science</option>
<option value="5">Fire &amp; Emergency Mgmt</option>
<option value="7">Healthcare</option>
<option value="8">Information Technology</option>
<option value="9">Legal/Paralegal Studies</option>
<option value="10">Liberal Arts</option>
<option value="11">Nursing</option>
<option value="12">Psychology &amp; Counseling</option>
<option value="13">Social Services</option>
<option value="14">Web/Graphic Design</option>
<option value="15">Theology</option></select></div></div></div>
          
            <input class="btn btn-warning btn-mine green-button" name="commit" type="submit" value="         Start Search         ">
            <!-- this will go to Student#create -->
            </fieldset>
          </form> <!-- end simple_form do block -->

app/views/question_steps/_form.html.erb
<%= nested_form_for @question, url: wizard_path do |f| %>
  <%= hidden_field_tag :question_id, @question.id %>
  <% if @question.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= yield f %>
  <div class="actions">
    <%= f.submit "Continue" %>
  </div>
<% end %>

app/views/question_steps/answer.html.erb
<h1>Enter Your Answers </h1>
<%= render layout: 'form' do |f| %>
  <% if f.object.answer_options.to_s == "2" %>
    <%= f.radio_button(:ansopt2, 'yes-no', :checked => true) %> yes-no <br>
    <%= f.radio_button(:ansopt2, 'true-false') %> true-false <br>
    <%= f.radio_button(:ansopt2, 'custom') %> custom <br>
    <div id="que_ans_custom" style="display:none;">
      <%= f.label :ans_custom_1 %>
      <%= f.text_field :ans_custom_1 %> <br>
      <%= f.label :ans_custom_2 %>
      <%= f.text_field :ans_custom_2 %> <br>

    </div>
  <% else %>
    <%= f.fields_for :answers do |ans| %>
      <%= ans.text_field :answer %>
      <%= ans.link_to_remove "Remove Answer" %>
    <% end %>
    <p><%= f.link_to_add "Add Answer", :answers %></p>
  <% end %>
  <br>
<% end %>

<script type="text/javascript">
$("#question_ansopt2_custom").click(function(){
  $("#que_ans_custom").show();
  $("#question_ans_custom_1").attr('required', true);
  $("#question_ans_custom_2").attr('required', true);
});
$("#question_ansopt2_yes-no").click(function(){
  $("#que_ans_custom").hide();
  $("#question_ans_custom_1").attr('required', false);
  $("#question_ans_custom_2").attr('required', false);
  });

$("#question_ansopt2_true-false").click(function(){
  $("#que_ans_custom").hide();
    $("#question_ans_custom_1").attr('required', false);
  $("#question_ans_custom_2").attr('required', false);

  });

</script>

app/views/question_steps/question.html.erb
<h1>Enter Your Question </h1>

<%= render layout: 'form' do |f| %>

  <div class="field">
    <%= f.label :form %>
    <%= f.select :form_id, Form.all(&:name).map{ |form| [form.name, form.id ]} %>
  </div>
  <div class="field">
    <%= f.label :question_name %>
    <%= f.text_field :question_name %>
  </div>
  <div class="field">
    <%= f.label :answer_options %>
    <%= f.radio_button(:answer_options, '2') %> 2 Options <br>
    <%= f.radio_button(:answer_options, '2+') %> More than 2 Options
  </div>

<% end %>

app/views/question_steps/selecttype.html.erb
<h1>Enter Your Type </h1>
<%= render layout: 'form' do |f| %>
  <div class="field">
  <%= f.label :question_type %>
  <% if f.object.answer_options.to_s == "2" %>
    <%= f.select :question_type_id, QuestionType.option2.all(&:name).map{ |form| [form.name, form.id ]} %>
  <% else %>
    <%= f.select :question_type_id, QuestionType.option2plus.all(&:name).map{ |form| [form.name, form.id ]} %>
  <% end %>    
  </div>
<% end %>

app/views/shared/_about_us.html.erb
<div style="padding:10px 20px 20px 20px;">
	<style>
		.dc { color:black; font-weight:bold;}
	</style>
	<p><span class="dc">DegreeCouncil.org</span> provides breaking news and reference material to help prospective students make solid decisions in this difficult economy. A thoughtful person – whether a fresh high school graduate, a first-time college student, or a mid-career professional – cannot jump into a degree program without being informed about current job demand, and job demand in the foreseeable future. According to the US Bureau of Labor Statistics (BLS), college graduates earn an average of 40% more money than those without a college education. Perhaps more startling is that people without a college degree are twice as likely to be unemployed than those with a college degree.</p>

<p><span class="dc">DegreeCouncil.org</span>, featuring “Answer Center” and daily updated career and degree news, empowers first-time students or those in mid-career, to make informed decisions that will lead to future job security, and hopefully, a successful, balanced life.</p>

<p>Furthermore, <span class="dc">DegreeCouncil.org</span> works directly with online colleges and universities and “on campus” schools, to ensure that all study programs and information are up-to-date – and that prospects who fill out the request for information will usually find out within 24 hours which schools and programs are just right for their schedules. Real school advisors will call prospective students and walk them through the whole process.</p>

<p>If you don’t find the answers you’re looking for on <span class="dc">DegreeCouncil.org</span>, please contact us at contact@sandhilldigital.com and we’ll have one of our team members get all your questions answered by email or phone (whichever you prefer).</p>

<p>Request Information <%= mail_to("info@sandhilldigital.com","Now",:subject => "information Request") %>, or <%= link_to("Browse","http://degreecouncil.org") %> the site to find your area of interest, or plug a keyword into our search box to quickly present relevant articles.</p>
</div>

app/views/shared/_facebook.mobile.erb
<script type="text/javascript">(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=152059254907400";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_federal_body_mobile.html.erb
	<div id="left_column_wrapper">
		
		<% unless flash[:notice].nil? %>
			<div id="notice"><%= flash[:notice] %></div>
		<% end %>
		
		<%= render "/shared/progress_bar" %>
		
		
		<div id="picform_main" >
			<h2>Federal Financial Aid</h2>
			<%= simple_form_for @student,  url: wizard_path,  :html => { :width => '95%' } do |f| %>
	
				<fieldset>
					<%= f.input :us_citizen, 
						:label => "Are you a U.S. citizen or a national or permanent resident of the U.S?", 
						# field of type boolean, simple-form will show it as a checkbox
						:wrapper_html => {:id => 'us_citizen', :class => 'inline'}
						%>
					<%= f.input :financial_aid,
						:label => "Are you interested in tuition assistance?",
						#:collection => ["Yes","No"],
						#:as => :radio_buttons,
						:wrapper_html => {:id => 'interest_title4', :class => 'inline'}					
						%>
					<!-- 
					<%= f.input :tuition_reimbursement,
						:label => "Are you interested in tuition reimbursement?",
						:wrapper_html => {:id => 'interest_reimbursement', :class => 'inline'}				
						%>
					-->								
					<%= f.input :military_tuition_assistance,
						:label => "Are you interested in military tuition assistance or Veterans Educational Benefits?",
						# field of type boolean, simple-form will show it as a checkb
						:wrapper_html => {:id => 'interest_military', :class => 'inline'}				
						%>
					
					
					<%= f.input :affiliated_with_us_military, 
						:label => "Are you affiliated with the U.S. military?", 
						# field of type boolean, simple-form will show it as a checkb')
						:wrapper_html => {:id => 'affiliated', :class => 'inline'}
						%>
				
					<%= f.input :type_of_military_affiliation, 
						:label => "Type of affiliation",
						#:as => :radio_buttons, 
						:collection => 
							[
								["None",0],
								["Veteran", 1],
								["Active Duty",2],
								["National Guard",3],
								["Reserve (active)",4],
								["Reserve (inactive)",5],
								["Active Duty Spouse",6],
								["Guard Spouse",7],
								["Reserve Spouse",8]
							],
						
						:wrapper_html => { :id => 'military_affiliation'} 
						 %>
					<%= f.input :branch_of_service, 
						:label => "Branch of service",
						#:as => :radio_buttons, 
						:collection => 
							
							[
								#["None",0],
				    		  	["Army",1],
				    		  	["Navy",2],
				    		  	["Air Force",3],
				    		  	["Marines",4],
				    		  	["Coast Guard",5],
				    		  	["Department of Defense (DOD)",6]								
							],
						:wrapper_html => { :id => 'branch'} 
						 %>
	
				  	<div class="form-actions" id="federal_submit">
						<!-- <## link_to "Back", previous_wizard_path, :class => 'btn' #> -->
						<%= f.submit 'Next', :class => 'btn-warning btn-large' %>
				  	</div>
				</fieldset>
	
			<% end %>
		</div>
	</div>

app/views/shared/_footer.mobile.erb
<div data-role="footer" data-theme="c" id="footer">
	<a data-rel="dialog" data-ajax="true" data-transition="pop" href="#aboutUs">About</a>
	<a data-rel="dialog" data-ajax="true" data-transition="pop" href="#contactUs">Contact</a>
	<a data-rel="dialog" data-ajax="true" data-transition="pop" href="#privacyPolicy">Privacy Policy</a>
</div>